site_name: 'ATLAS Custom Display Guide'
site_description: 'F1-grade engineering telemetry visualizations'
docs_dir: 'docs'
repo_url: https://github.com/StevenMorganMcLaren/DisplayAPI.Site.git

nav:
  - Home:
    - ATLAS 10: index.md
    - Features: home/features.md
    - Prerequisites: home/prerequisites.md
  - Display API Overview:
    - Introduction: overview/index.md
    - Further Information:
        - Model-View-ViewModel: overview/mvvm.md
  - Developer Guide:
    - Overview: devguide/index.md
    - Tutorials:
      - Create Display from Scratch: devguide/tutorials/createfromscratch.md
      - Prerequisites: devguide/tutorials/prerequisites.md
      - Samples Support Library: devguide/tutorials/samplessupportlibrary.md
    - Enhancing Displays:
      - Factories and Services: devguide/detailed/factoriesandservices.md
      - Initialization, state and notifications: devguide/detailed/initialization.md
      - Working with Display Properties: devguide/detailed/displayprops.md
      - Working with Sessions: devguide/detailed/sessions.md
      - Working with Timebase and Cursor: devguide/detailed/timebasecursor.md
      - Working with Display Parameters: devguide/detailed/parameters.md
      - Working with Data: devguide/detailed/data.md
      - Good Citizenship: devguide/detailed/goodcitizenship.md
    - Further Information:
        - Core API: devguide/coreapi.md
        - API Limitations: devguide/limitations.md
  - API Reference: "https://mat-docs.github.io/Atlas.DisplayAPI.Documentation/index.html"

theme:
  name: 'material'
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.integrate

copyright: Copyright &copy; 2021 McLaren Applied Ltd.

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true