site_name: 'ATLAS Display API'
site_description: 'Creating custom displays for McLaren ATLAS'
docs_dir: 'docs'
repo_url: https://github.com/mat-docs/ATLAS.DisplayAPI.Site
edit_uri: edit/main/docs/
site_url: https://docs.atlas.mclarenapplied.com/developer/atlas-displayapi/

theme:
  name: 'material'
  palette:
    primary:  'black'
    accent:   'indigo'
  custom_dir: overrides
  # assets/swoosh is cached aggressively - rename if icons change
  favicon:    'assets/swoosh/favicon.png'
  logo:       'assets/swoosh/logo.png'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.integrate

copyright: Copyright &copy; 2021 McLaren Applied Ltd.

nav:
  - ⇱ Docs Portal: https://mclaren-atlas-docs.netlify.app/
  - Introduction:
    - Overview: index.md
    - Further Information:
        - MVVM: introduction/mvvm.md
  - Developer Guide:
    - Overview: devguide/index.md
    - Tutorials:
      - devguide/tutorials/prerequisites.md
      - devguide/tutorials/createfromscratch.md
      - devguide/tutorials/samplessupportlibrary.md
    - Enhancing Displays:
      - devguide/detailed/factoriesandservices.md
      - devguide/detailed/initialization.md
      - devguide/detailed/displayprops.md
      - devguide/detailed/sessions.md
      - devguide/detailed/timebasecursor.md
      - devguide/detailed/parameters.md
      - devguide/detailed/data.md
      - devguide/detailed/goodcitizenship.md
    - Further Information:
        - devguide/coreapi.md
        - devguide/limitations.md
  - API Reference: "https://mat-docs.github.io/Atlas.DisplayAPI.Documentation/index.html"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
